### ISSUE TITLE
$entity->findBy(["type" => 2])->order(...)

### ISSUE THREAD

**Issue by JanSuchanek** [nextras/orm-demo-nette#3]
Hi, is possible to find chields entitie for example like $entity->findBy(["type" => 2])->order(...) and sort?
Or it's bad practice?

**Comment by hrach** [comment]
I do not understand. You can filter collections not entities.

**Comment by hrach** [comment]
But feel tree to ask in czech, or provide real example :)

**Comment by JanSuchanek** [comment]
Sry, lze filtrovat kolekce získaných entit u vazby 1:m?
Mám entitu, která má vazbu 1:m na kolekci entit.

$author->books

Lze ovlivnit jaké knížky se zobrazí případně jak budou seřazené?

**Comment by hrach** [comment]
Samozrejme a je velmi to velmi caste. Pokud se filtrace opakje, pak je vhodne vytvorit virutalni property, jejiz getter to dofiltrje.

**Comment by JanSuchanek** [comment]
Můžeš mi prosím napsat příklad jak bys filtroval autorovi knížky z entity $author?

Já pochopil že za books by měl být ->get() (jen nevím důvod, a teprve pak where a orderBy ) 
nebo rovnou ->findBy([ ... ])?

Zkusim ještě pohledat v testech.

Tzn.: takto https://github.com/hrach/orm-demo/blob/master/app/model/orm/posts/Post.php

Vyzkouším, jen sem si nebyl jistej, jaké dotazy to bude generovat, když bych filtroval nad kolekcí 
$this->orm-->authors->findBy[[])-> ...

Každopádně Nextras\ORM je pěkná knihovna.

**Comment by hrach** [comment]
Pokud filtrujes kolekci z vazhy hasMany, je jeji efektivni nacitani zachovano. Tzn. jak v odkazovanem souboru ,get() a pak findBy(), pripadbe orderBy a limitBy().

**Comment by JanSuchanek** [comment]
Ok vyzkouším dík.
