### ISSUE TITLE
Probably bad relationship type

### ISSUE THREAD

**Issue by zraly** [nextras/orm-demo-nette#5]
Post - tag is not a self-referencing relationship, so maybe there should be `m:n` instead of `m:m`?

https://github.com/nextras/orm-demo/blob/master/app/model/orm/tags/Tag.php#L14
https://github.com/nextras/orm-demo/blob/master/app/model/orm/posts/Post.php#L21

**Comment by hrach** [comment]
m:n or m:m or n:n or n:m are synonyms. the correct form is m:m as (many to many), other versions are deprecated and should be removed in the future.
